const images = {
  groupomania: "/images/groupomania.webp",
  hrnet: "/images/devevoke-hrnet.png",
  kanap: "/images/kanap.webp",
  piquante: "/images/piquante.webp",
  chouetteAgence: "/images/devevoke-chouette.png",
  ohmyfood: "/images/devevoke-ohmyfood.png",
  gameOne: "/images/devevoke-gameone.png",
  fishEyes: "/images/devevoke-fisheyes.png",
  kasa: "/images/devevoke-kasa.png",
  pictureHeader: "/images/bg-4.webp",
  footerBackground: "/images/backgroundContact.webp",
  backgroundDecoBlack: "/images/background1.webp",
  optiRankPicture: "/images/pictures1.webp",
  callToActionPicture: "/images/projet.webp",
  bannerPicture1: "/images/a_propos.webp",
  bannerPicture2: "/images/bg-1.webp",
  bannerPicture3: "/images/bg-2.webp",
  bannerPicture4: "/images/bg-3.webp",
  bannerPicture5: "/images/bg-5.webp",
  contactBackground: "/images/imageContact.webp",
  reactImage: "/images/react-image.png",
  nextImage: "/images/next-image.png",
  reduxImage: "/images/redux-image.png",
  symfonyImage: "/images/symfony-image.png",
  etudeImage: "/images/etude-image.png",
  formationImage: "/images/formation-image.png",
  passionImage: "/images/passion-image.png",
};

export default images;
