import React from "react";

export const metadata = {
  title: "DevBreath",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" suppressHydrationWarning={true}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script
          defer
          src="https://kit.fontawesome.com/53013b6bdc.js"
          crossOrigin="anonymous"
        ></script>
        <title>DevBreath</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
