const images = {
  kellerWilliams: "/images/kw.png",
  hrnet: "/images/hrnet.png",
  argentBank: "/images/argentBank.png",
  piquante: "/images/piquante.webp",
  chouetteAgence: "/images/devevoke-chouette.png",
  ohmyfood: "/images/ohmyfood.png",
  fenixSolutions: "/images/fenixSolutions.png",
  fishEyes: "/images/fisheyes.png",
  kasa: "/images/kasa.png",

  pictureHeader: "/images/bg-4.webp",
  footerBackground: "/images/backgroundContact.webp",
  backgroundDecoBlack: "/images/background1.webp",
  optiRankPicture: "/images/pictures1.webp",
  callToActionPicture: "/images/projet.webp",
  bannerPicture1: "/images/a_propos.webp",
  bannerPicture2: "/images/bg-1.webp",
  bannerPicture3: "/images/bg-2.webp",
  bannerPicture4: "/images/bg-3.webp",
  bannerPicture5: "/images/bg-5.webp",
  contactBackground: "/images/imageContact.webp",
  reactImage: "/images/react-image.png",
  nextImage: "/images/next-image.png",
  reduxImage: "/images/redux-image.png",
  symfonyImage: "/images/symfony-image.png",
  etudeImage: "/images/etude-image.png",
  formationImage: "/images/formation-image.png",
  passionImage: "/images/passion-image.png",
};

export default images;
